### ISSUE TITLE
Suggestion: add a "touch all" function to Form controls

### ISSUE THREAD

**Issue by renatodantas** [noahsalvi/svelte-use-form#23]
I have a situation where I reuse a form within a Bootstrap's modal declared once in a page. This page has a list of items and the user can select one to edit its data in the form or click at a button to pass empty data to form to save a new item.

![image](https://user-images.githubusercontent.com/11853349/140386935-dbc89b1a-9136-48f9-8d8b-f543c0797dac.png)

Each time I open modal I call `$form.reset()` to clean validations and read fresh data, either from selected item or new blank item. PS.: without leaving page and reusing declared form at modal.

However, if I launch a modal to fill new item data and ignore fields filling (not "touching" them and hitting submit button), validation fails and let form submit proceed as valid. I needed to add the following code before submit to proper handle validation errors:

```javascript
Object
   .keys($form)
   .forEach(field => $form[field].touched = true);
```

Am I doing something wrong? Or the form submit is working as expected and missing a "touch all fields" function?

BTW, congrats for the amazing component.

**Comment by noahsalvi** [comment]
Regarding touchAll()
I like the idea :)
I'll let you know when it's implemented. (probably today or tomorrow)

About your specific use case. Could you create a svelte REPL for it? If not I'll try to recreate it myself

**Comment by noahsalvi** [comment]
Thanks for the detailed explanation!

Actually there already is a touch all functionality. `$form.touched = true` will set every form control to touched.

The main problem that you're facing isn't about the controls not being touched or validated. It's about how you set the new values of the input.
At the moment you're binding the `person.nome` property to the `nome` input and when the value changes, it updates the input correctly but not the internal logic of svelte-use-form. This is due to the fact, that setting the value of an input doesn't start any events that notify svelte-use-form of the change. 

**Clarifications**
1. You shouldn't change input values directly by setting the `value` attribute at runtime. Although you can use the `value` attribute to set the initial value statically. 
2. `reset()` sets the value of the input to the value it had when it was rendered (initial value). 

# Solutions for the internal state not being updated
## 1. Key Solution
Wrap the form with `{#key person}...{/key}` and set nomes `value` to the desired new value. This will recreate the form every time `person` is changed and therefore display the new initial value.

## 2. Updating it manually
After updating the value of the input by binding or setting it programatically, update the svelte-use-form state of the control by running e.g. `$form.nome.value = person.nome` 
This only works if you aren't running $form.reset() before hand.
```typescript
export const open = () => {
    showDialog = true;
    $form.touched = false;
    $form.nome.value = person.nome;
    console.log("person:", person);
  };
```
## 3. Set the value by resetting
Remove the binding on the input and change the value of the input by using the reset method on the control: `$name.nome.reset({ value: person.name })`
This will update the input value and also its internal state.

## 4. Change the value (coming next update)
Remove the binding on the input and set the value by running the change method `$form.nome.change(person.nome)`
This will do the same thing as `$form.nome.reset({ value: person.nome })`, except that it won't set the input to untouched if it was touched.

# Problem with your specific example
You're updating the values of the form like this:
``` typescript
const editPerson = async (person) => {
    selectedPerson = { ...person };
    dialog.open();
  };
```
The problem is that even though you're changing the `selectedPerson` before opening it, the component "SupposedDialog.svelte" will still have the same reference of `person` since svelte only updates it after the current tick has ended. Solution is to await tick() [Docs](https://svelte.dev/docs#tick)

**Solution**
``` typescript
const editPerson = async (person) => {
    selectedPerson = { ...person };
    await tick();
    dialog.open();
  };
```

**Comment by renatodantas** [comment]
Thanks @noahsalvi and sorry for the late response.

The `key` solution didn't solved the problem, because each time user type some info on the inputs, Svelte refreshes components and looses focus, transforming it in a poor user experience.

The `await tick()` solution solved some rendering problems.

In the end, updating form values manually (individual input resetting) was the definitive solution.
