### ISSUE TITLE
Using Submit without disabled button... 

### ISSUE THREAD

**Issue by zipzit** [noahsalvi/svelte-use-form#26]
I've got a problem.  I don't believe my users are capable of understanding a greyed out, non operative Submit button.  I really know these users, and they are confused easily.  I need things simple, really simple.  

I was hoping to use `<input...  use:validators={[required]}`,  then use the `Hint` field to display _This is a Mandatory Entry_ for each and every mandatory question upon Button Submit.  Clearly the system doesn't work that way.  

Start with [simple login example..](https://svelte.dev/repl/ca967b45a5aa47b2bb2f9118eb79eefe?version=3.44.3) 

Go to Line # 19 and change ` <button disabled={!$form.valid}>Login</button>` to ` <button>Login</button>`

That's it.  Hit the Submit button.  Instead of the `<Hint>` element populating, what I see is the HTML5 Built-in form validation  features warning popup.  Image attached.
![Screenshot from 2022-01-01 23-28-53](https://user-images.githubusercontent.com/4413134/147869213-04f17f06-39f9-40d2-9678-c75625d43ce2.png)

Am I doing this right?  Can I get there from here?  Or should I consider alternate Svelte Form Validation libraries?  

Note: I've been playing with Svelte Conditional stuff... 

    {#if $form.login?.errors}
        <div class="customHint">This question is required.</div>
    {/if}

And that's pretty much a fail.  The message displays all the time.  I'm trying to keep this real simple.  Button groups everywhere.  `.touched` doesn't really make any sense, so I can't really `{#if $form.login?.touched && $form.login?.errors}`    And there is no element state for "Scrolled right on thru", sigh.

**Comment by zipzit** [comment]
Its not perfect, but I think I found a reasonable solution. This keeps the required `Hint` from being displayed until the Submit button is pressed.  

    <button on:click="{$form.touched = true}">Login</button>

**Comment by noahsalvi** [comment]
Hey zipzit
My apologies for the delay 😓

No worries, I don't mind questions as issues since this repo is still small :)
Furthermore I do not believe that people will actually use the tag on SO 🤷‍♂️

The thing with svelte-use-form is, that it was built for a different "form flow" as the one that you want to implement. The intended flow is to validate the fields one by one and only when all the needed validators are OK to submit the form. Meaning, that if you enter an invalid email address in the login example, you'll be prompted to fix it before continuing to the next field. 

If I understand your flow correctly, you want to show the user the hints only after they have pressed the submit button right?
I would probably try a similar approach to yours:
https://svelte.dev/repl/c82268b91b394300967f800a46b68037?version=3.44.3
or which is shorter
https://svelte.dev/repl/68c22ce957164636be33a3bd01b4e025?version=3.44.3

**Comment by zipzit** [comment]
Odd.  What is the criteria for choosing a form validation library?  
1) Consistency with the foundation being used.  (in this case, Svelte/Sveltekit)
2) Ability to customize validation messages and other styling clues (incl. border box colors)
3) Small package size
4) Open source, with reasonably active support base.  (i.e. a repo with no commits in the past five years, probably no go.)
5) Validation upon touch / focus / blur OR SUBMIT  (Yes I know you didn't ORIGINALLY design it that way, but you don't know my customers like I do.)
6) Good documentation, including an assortment of samples and tips/ tricks / hints. If the original author is busy, we all understand that.. there should be a friendly mechanism for users to submit ideas and recommendations.  I will say, if svelte.dev/repl are that mechanism, then the home page readme should be friendly enough for us to perfom pull requests to support that effort. 
7) An active support base, where users can share experiences (StackOverflow?  Support forum? Github Issues, [Github discussions](https://docs.github.com/en/discussions/quickstart)?)

Easy customization without code rewrites is obviously preferred.  

I will say, I like what you've done here, and the project is flexible enough to function for most of my needs.  Many thanks to you (and support folks ) for your efforts here.  I'm very appreciative.  

The next place I want to go is the use of a hint, that is really a hint.   Remember my use case is pretty far out there.  I'm using a form with multiple choice radio buttons to teach skills.  I'm using the validator as an additional quiz/ test / answer / think, fricking think! process.  I want to provide a hint, that the user COULD choose and successfully submit.  

I suspect I could play games in the custom validator functions.  I haven't yet gotten to that step.  Minimal Viable Product first...

Here's sort of where I'm going... 
 
![Screenshot from 2022-01-06 20-34-51](https://user-images.githubusercontent.com/4413134/148492609-5c74f55a-fdc5-4968-9312-2730823e4fb5.png)

**Comment by noahsalvi** [comment]
You're right.

I'll enable Github Discussions for this repo.

Regarding your next use case. As you know, radio buttons are a group of inputs sharing a common name property. This leads to the problem, that you can't validate each button separately, since they all represent one "form control". The solution for the moment would be to create a validator that checks if the value of the radio buttons is a wildcard and in that case set an error with a flag, which you can use in the Hint via `let:value` to conditionally render different messages.
I would probably do something like this.
https://svelte.dev/repl/16008fe7fc6744e2a7fb006001b7ab9d?version=3.45.0

This is sadly a limitation set by HTML radio buttons 😓
