### ISSUE TITLE
Custom validation typing error

### ISSUE THREAD

**Issue by szattila98** [noahsalvi/svelte-use-form#50]
Hello, I wanted to write a custom validator, using the example provided in the readme, but typescript expect a generic argument for `From` and I cannot understand what it needs. Could you help me please, what should be done about this? I used any as a workaround but it is not really idiomatic.
I provided a screenshot about the problem, as you can see it needs a generic argument named `Keys` that extends `string | number | Symbol`.
![image](https://user-images.githubusercontent.com/37137309/229285074-b309366b-5d5f-4f7b-8289-81255128b8ec.png)

**Comment by noahsalvi** [comment]
Hi, thank you for bringing this to my attention. You're right the example isn't up to date anymore.
The last version 2.5.0 introduced better typings which do the [following](https://github.com/noahsalvi/svelte-use-form#why-specify-formproperties). The generic `Keys` expects the names of the inputs/fields in the form so that it can type them correctly when accessing the e.g. `$form`.

## Solution
### Recommended Solution
`form: typeof $form`

In your example if you decided to statically define the name of the fields in your form in the `useForm` function, you would then benefit from having intellisense in the custom validator function.
 = `form.password.value` would not throw `'form.password' is possibly 'undefined'`
 
### Alternative Solution
`form: Form<any> & FormControlsUnspecified`

This is a general solution which doesn't reference a specific form.
 
## Remark
It would be nice to have an additional type for the `Form` which doesn't require to pass in the keys, so that it can be used in cases where you don't want the validator definition to be coupled to a specific form.

The following would be a working example. Feel free to comment on this.
![image](https://user-images.githubusercontent.com/46045829/229306452-68196ca4-e6b3-4b41-aecb-15031d16d065.png)

**Comment by szattila98** [comment]
The alternative solution works and the new type is a very good idea.
But the first one would be better as I like typings, sadly it does not work for me, as you can see on my screenshot it says that `$form` is not defined.
![image](https://user-images.githubusercontent.com/37137309/229336861-a9b9beac-5b28-4868-8725-9d5c44dfa483.png)

**Comment by szattila98** [comment]
Sorry, I just took a quick look and it looked good, but now I see that the alternative solution also has problems, as you can see the validator function is OK, but if I want to use it on an input, it has a type error.
![image](https://user-images.githubusercontent.com/37137309/229346888-aff01e82-334e-416c-823d-9c75585fdaf2.png)
![image](https://user-images.githubusercontent.com/37137309/229346878-c9188dc7-dfec-4133-9008-d566fd69e3da.png)

**Comment by noahsalvi** [comment]
No you didn't miss anything - I did. There seems to be a bigger underlying problem that I will try to resolve but for now I've  published a patch for this problem. Included in version **2.6.2**.

You should now be able to use it after updating like [this](https://github.com/noahsalvi/svelte-use-form#custom-validator)
Please let me know if this works for you.

Regarding my first suggested solution, you can disregard it for now.

**Comment by szattila98** [comment]
It works as expected. You are really fast and awesome, thank you for the quick patch.  ❤️
