### ISSUE TITLE
BUG:Unable to get the value of svelte-select

### ISSUE THREAD

**Issue by ljm000** [noahsalvi/svelte-use-form#51]
I used svelte-select as select plugin
The value of svelte-select exists in a hidden input
![image](https://user-images.githubusercontent.com/12406935/235051935-2ef1bc01-4110-4722-82de-c699b8db2b49.png)
![image](https://user-images.githubusercontent.com/12406935/235051972-e371ed5a-bc95-45e7-8898-4968a0bb0dc3.png)

```
<script>
  import Select from "svelte-select@5.6.0";
	import { useForm } from "svelte-use-form@2.6.2";
	const form = useForm();
  let collection = [
    { value: 1, label: "one" },
    { value: 2, label: "two" },
    { value: 3, label: "three" }
  ];
</script>

<form use:form>
	<input name="test" >
<Select name="select" items={collection} />

</form>

<pre>
{JSON.stringify($form, null, " ")}
</pre>
```
This is a simplified example
[svelte-app.zip](https://github.com/noahsalvi/svelte-use-form/files/11349701/svelte-app.zip)

**Comment by noahsalvi** [comment]
Hey, sorry for the delay.

I wouldn't really call this a bug, since svelte-use-form is only expected to work with native HTML5 inputs and in some cases simple components wrapping them.
Still, I'm always open to adding features that can benefit the users of this library if they are sensible. In this case I do not really see an easy fix for making both libraries compatible, since besides how they concretely generate these selects, they also have a special format for the selects input value. This would require a lot of changes to the core logic of this library and would make this library dependent on their implementation.

![image](https://github.com/noahsalvi/svelte-use-form/assets/46045829/580fa55f-555d-4c20-9ed9-6fc769dcac2f)

I'm closing this issue for now but feel free to comment if you believe that there would be a way to make these libraries compatible without the prescribed issues.
