### ISSUE TITLE
[Feature Request] store custom error message in FormControl Class

### ISSUE THREAD

**Issue by niklasgrewe** [noahsalvi/svelte-use-form#6]
Hi, thanks for this library to make form validation easier in svelte 👍 It is possible to integrate custom error messages in the FormControl Class? 

I would imagine it like this. You can define custom error messages for each validator like this:

```js
const form = useForm({
   email: { validators: [email, required], errors: { email: "This is not a valid email address", required: "This field is required" } }
});
```
the FormControl Class looks like this:

```json
"email": {
  "errors": {
   "required": "This field is required",
   "email": "This is not a valid email address"
  },
  "valid": false,
  "touched": false,
  "validators": [
   null,
   null
  ],
  "initial": "",
  "_value": ""
 },
 ```
 I might be easier to define error messages in one place and can access them, via the FormControl Object

**Comment by noahsalvi** [comment]
Hey Niklas

How would you use these custom error messages in your form?

```svelte
```

**Comment by noahsalvi** [comment]
Upps didn't close it on purpose

**Comment by noahsalvi** [comment]
Hey Niklas

Could you give me a complete example on how you would use these custom validation messages in your component?

**Comment by noahsalvi** [comment]
yeah, your example helped :)

Currently formControl.errors returns a map of all active validation errors, would in your example formControl.errors return only the value of the error (message)? Because if yes, that would be a problem for people trying to access errors directly e.g. `formControl.errors.email && formControl.errors.minLength`
or 
`<HintGroup for="randomInput" on="email">RANDOM_TEXT<HintGroup>`

**Comment by niklasgrewe** [comment]
yes, that's what I thought. If you say that it will be difficult to implement something like that, then we can do it differently. It would only be important to me if i can define the error messages within the `useForm()` function and access them via the FormControl Object.

**Comment by noahsalvi** [comment]
I see.
One thing that I'm wondering right now is, how would the user, when he for example uses minLength and sets a custom message, get the length? Like when he has minLength(4) and want's to display the length in the final text.

Maybe something like this?
``` typescript
const form = useForm({
  title: { 
    validators: [minLength(4), required], 
    messages: { minLength: value => `Title must be at least ${value} characters long`, required: "The title field is required" } }
});

console.log($form.email.minLength);
// "Title must be at least 4 characters long"

console.log($form.email.messages);
// { minLength: "Title must be at least 4 characters long", required: "The title field is required" }
```

There could also be a property for getting only the most important error message dynamically like in your first example but that brings the problem with it, that we would have to choose which validators are ranked higher than others and what about when we want to use custom validators, how would those behave? So for this part of the feature, I think that it's better that each person implements it themselves.
I wrote this repl showing two possible implementations
https://svelte.dev/repl/d6043931e6a64418a26244d3738f1504?version=3.35.0

**Comment by noahsalvi** [comment]
My bad, I should have explained better, what I mean by the two terms.

form one uses a function that has a constant map called VALIDATOR_HIERARCHY, that is used to determine the order of the validators. That means you can add the validators in any order you'd like and it will always follow the same order.

form2 basically does what you suggested
> i think it would be nice, if we can control it in the validators array. So the first index is the highest ranked validator and the last validator is the last one in the ranking. For example, if you define these validators:

form2 uses a function that returns the first object in the errors array and that is the one the farthest to the left, since FormControl.validate starts at validator index 0 and goes upwards.

In regards to  simplifying it, doing it like you proposed would mean, that every user has to specify a custom message and that would conflict with my goal of keeping things as simple as possible and keeping the validation messages in the dom.
But if someone still wanted to use it like in your example, they could create wrappers of the functions they'd like to use which take in a custom message or even a function that can wrap every validator with a custom message.

e.g. wrapper for required
``` typescript
import { required as sRequired } from "svelte-use-form";

export function required(message: string) {
  return (value) => sRequired ? null : { required: message };
}
```

**Comment by niklasgrewe** [comment]
thank you for your explanation, i get it. Personally, I would prefer the form2, because you get more control over when which error is displayed. Could you implemte that feature so that in the end you can use it something like this?

```js
const form = useForm({
  title: { 
    validators: [minLength(4), required], 
    messages: { minLength: value => `Title must be at least ${value} characters long`, required: "The title field is required" } }
});

console.log($form.email.minLength);
// "Title must be at least 4 characters long"

console.log($form.email.messages);
// { minLength: "Title must be at least 4 characters long", required: "The title field is required" }
```

**Comment by noahsalvi** [comment]
Yeah that should work!
I'll work on it when I get time.

Btw I was wondering why you chose against using Hint components for displaying custom messages. Do you prefer to keep the messages in typescript?

**Comment by niklasgrewe** [comment]
cool thank so much 👍 i can't wait to use it. 

I am using tailwindcss to develop my user interface. Its important to me, that i have enough customization to build my own ui. I don't notice that i can style the Hint Components or use custom css. So i only need the row values and wrapp it in my styles.

**Comment by noahsalvi** [comment]
ErrorMap is now implemented https://github.com/noahsalvi/svelte-use-form/releases/tag/2.1.0
You can use it like in your example but instead of messages it's called errorMap and it will map the validation errors before setting them on the error object. So if you want to retrieve the first error message, you can get it by something like 

`const get = (formControl) => Object.values(formControl.errors)[0] ?? ""; `


Btw I've now added support for directly setting classes on Hint components but even without it you could still do it like this.
https://svelte.dev/repl/71e4a0bc1147498faa622acdc51c12df?version=3.35.0


Danke für's helfen 👍

**Comment by niklasgrewe** [comment]
@noahsalvi As you mentioned, i grap the first error like this in my `input.svelte` comp...

```js
{#if touched && errors}
   <p class="mt-2 text-sm text-yellow-600" id="email-error">{Object.values(errors)[0]}</p>
{/if}
```
Everhing works as i expected, but when i enter `niklas@grewe` i get `undefined`, instead of `This is not a valid email address` I had the same problem before in one of your REPL. I suspect that the error is due to the email validator, as it considers niklas@grewe to be a valid email address, which of course is not correct. Could you check this?

**Comment by noahsalvi** [comment]
Actually `niklas@grewe` is a valid email according to the specs. https://stackoverflow.com/questions/20573488/why-does-html5-form-validation-allow-emails-without-a-dot

If you want one that also requires a dot in the email you could create one like this

``` javascript
function email(value) {
  const emailRegex = /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/gm;
  if (!emailRegex.test(value)) return { email: "Email not valid"};
}
```
