### ISSUE TITLE
Validity is not reevaluated after variable assignment

### ISSUE THREAD

**Issue by keehun** [noahsalvi/svelte-use-form#60]
When an `<input>` has `bind:value={something}`, updating `something` doesn't trigger reevaluation of the validator like it would had the field been updated by the user. Is there an event I should trigger manually to get the same user-code-paths to be fired?

**Comment by noahsalvi** [comment]
Sorry, I do not have an answer to this problem. The thing is that `bind` uses `inputElement.value = newValue` to update the input elements value and as far as i am aware this does not create any events or call any hooks which we could observe to update the state of the internal form...

So as an alternative I would suggest to use reactive statements `$:` and call the `change` method of the form control.
This is sadly quite verbose and would in this example only represent a one way data flow. 

``` typescript
let value = "";
const updateFunction = (v) => $form.email?.change(v);
$: updateFunction(value);
```

(Disclaimer: Update to at least 2.9.1 since there was a bug where `change` wouldn't update the listeners.)

Feel free to share suggestions.

**Comment by keehun** [comment]
Thanks! This makes sense. Please feel free to close the issue if you don't think there's any systematic workaround or a solution fit for a library to implement.
