### ISSUE TITLE
Any way to pass use:validators in a custom component with an input inside?

### ISSUE THREAD

**Issue by Blankeos** [noahsalvi/svelte-use-form#64]

**Comment by noahsalvi** [comment]
Since svelte actions can only be used on native elements and not custom components I see the following two solutions:
1. Create a new property in your custom component which receives a list of validators and then modify the input element of the component to take in the validators using the property. `<input ... use:validators=validatorsProperty`

2. Use the parameter of the useForm call to pass in the validators. `const form = useForm({ email: { validators: [required, email] } });`
