### ISSUE TITLE
Run validation on submit

### ISSUE THREAD

**Issue by ryanballa** [noahsalvi/svelte-use-form#9]
Is there an example of how one would run validations on submit? I'd like to keep the submit active and allow users to click it but only proceed if no errors are present. I'd also like all the errors to show if they should be visible.

**Comment by noahsalvi** [comment]
Hey Ryan

I've now updated svelte-use-form to `2.2.0`.
By setting the new property `touched` on the $form object, you'll set touched = true to every form control in the form. This results in Hints being shown and the .touched class being added to the inputs.
Since svelte-use-form validates on mount and when anything changes in the fields, a manual validation is not required.

Here's the example you're looking for [REPL](https://svelte.dev/repl/984671a7737a4aceb59735d26dc86005?version=3.35.0)

And thanks for pointing out this use case!
